sudo: required
dist: trusty
language: java

branches:
  only:
  - master

jobs:
  include:
    - stage: build producer & consumer
    - script:
      - cd flight-producer
      - ./gradlew test
      - ./gradlew bootJar
      - cd ..
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t producer ./flight-producer
      - docker tag producer $DOCKER_USERNAME/producer
      - docker push $DOCKER_USERNAME/producer
      script:
      - cd flight-consumer       
      - ./gradlew test
      - ./gradlew bootJar
      - cd ..
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t consumer ./flight-consumer
      - docker tag consumer $DOCKER_USERNAME/consumer
      - docker push $DOCKER_USERNAME/consumer
