language: java
install: true

os: linux
dist: trusty

jdk:
  - openjdk11

script:
- cd flight-producer
- ./gradlew bootJar
- cd ..
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build -t producer ./flight-producer
- docker tag producer $DOCKER_USERNAME/producer
- docker push $DOCKER_USERNAME/producer
- cd flight-consumer       
- ./gradlew bootJar
- cd ..
- docker build -t consumer ./flight-consumer
- docker tag consumer $DOCKER_USERNAME/consumer
- docker push $DOCKER_USERNAME/consumer
- docker build -t visualization ./flight-visualization
- docker tag visualization $DOCKER_USERNAME/visualization
- docker push $DOCKER_USERNAME/visualization
