/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package pl.edu.pwr.raven.flightproducer.avro;

/**
 * Type of flight
 */
@org.apache.avro.specific.AvroGenerated
public enum FlightType implements org.apache.avro.generic.GenericEnumSymbol<FlightType> {
    International, Regional, Domestic;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FlightType\",\"namespace\":\"pl.edu.pwr.raven.flightproducer.avro\",\"doc\":\"Type of flight\",\"symbols\":[\"International\",\"Regional\",\"Domestic\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
