/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package pl.edu.pwr.raven.flightproducer.avro;

/**
 * Indicator whether the flight was cancelled or completed
 */
@org.apache.avro.specific.AvroGenerated
public enum FlightStatus implements org.apache.avro.generic.GenericEnumSymbol<FlightStatus> {
    Confirmed, Cancelled;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FlightStatus\",\"namespace\":\"pl.edu.pwr.raven.flightproducer.avro\",\"doc\":\"Indicator whether the flight was cancelled or completed\",\"symbols\":[\"Confirmed\",\"Cancelled\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
